version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-example}
    networks:
      - quikpad-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_URI: mongodb://root:${MONGO_PASSWORD:-example}@mongo:27017/
      MONGO_DB: quikpad
      NOTES_COLLECTION: quikNotes
      CODES_COLLECTION: quikCodes
      NODE_ENV: production
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
      - quikpad-network
    

  hub-app:
    build:
      context: ./apps/hub
      dockerfile: Dockerfile
      args:
        VITE_QUIKNOTE_URL: ${QUIKNOTE_URL}
        VITE_QUIKCODE_URL: ${QUIKCODE_URL} 
    restart: always
    ports:
      - "6010:80"
    networks:
      - quikpad-network

  note-app:
    build:
      context: ./apps/note
      dockerfile: Dockerfile
      args:
        VITE_API_ENDPOINT: ${API_ENDPOINT}
    restart: always
    ports:
      - "6011:80"
    networks:
      - quikpad-network
    
  code-app:
    build:
      context: ./apps/code
      dockerfile: Dockerfile
      args:
        VITE_API_ENDPOINT: ${API_ENDPOINT}
    restart: always
    ports:
      - "6012:80"
    networks:
      - quikpad-network


volumes:
  mongo_data:

networks:
  quikpad-network:
    driver: bridge